name: Build Blender Binary

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    
    steps:
      - name: Install Host-side Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential git ccache clang lld \
            libx11-dev libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev \
            libxxf86vm-dev libxfixes-dev libegl-dev wayland-protocols libpulse-dev \
            libwayland-dev libxkbcommon-dev libdbus-1-dev curl unzip libomp-dev
        
      - name: Checkout Blender
        uses: actions/checkout@v4
        with:
          repository: blender/blender
          path: blender
          ref: blender-v4.2-release
          fetch-depth: 1
          submodules: true

      - name: Fetch LFS
        run: |
          cd blender
          git config lfs.url "https://projects.blender.org/blender/blender.git/info/lfs"
          git lfs pull

      - name: Fetch Dependencies
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: AirmailTerror80/Meow.
          run_id: 37148520937
          path: ${{ github.workspace }}/build_deps/Release

      - name: Unpack Dependencies
        run: |
          export LIBDIR="${{ github.workspace }}/build_deps/Release"
          find "$LIBDIR" -type f \( -path "*/bin/*" -o -name "*.so*" -o -name "*.sh" \) -exec chmod +x {} +
          ls -lha "$LIBDIR"

      - name: Fetch CCache
        uses: hendrikmuhs/ccache-action@v1.2.23
        with:
          key: ${{ runner.os }}-aarch64-blender-4.2-bin
          restore-keys: ccache-Linux-aarch64-blender-4.2-bin
          max-size: 2G
          create-symlink: true

      - name: Build Blender
        run: |
          export LIBDIR="${{ github.workspace }}/build_deps/Release"
          
          mkdir -p $(pwd)/bin
          
          cat << 'EOF' > $(pwd)/bin/clang
          #!/bin/bash
          exec ccache /usr/bin/clang "$@"
          EOF
          chmod +x $(pwd)/bin/clang
          
          cat << 'EOF' > $(pwd)/bin/clang++
          #!/bin/bash
          exec ccache /usr/bin/clang++ "$@"
          EOF
          chmod +x $(pwd)/bin/clang++

          ln -sf $(pwd)/bin/clang $(pwd)/bin/cc
          ln -sf $(pwd)/bin/clang $(pwd)/bin/gcc
          ln -sf $(pwd)/bin/clang++ $(pwd)/bin/c++
          ln -sf $(pwd)/bin/clang++ $(pwd)/bin/g++
          
          ln -sf $(pwd)/bin/clang $(pwd)/bin/aarch64-linux-gnu-gcc
          ln -sf $(pwd)/bin/clang $(pwd)/bin/aarch64-linux-gnu-cc
          ln -sf $(pwd)/bin/clang++ $(pwd)/bin/aarch64-linux-gnu-g++
          ln -sf $(pwd)/bin/clang++ $(pwd)/bin/aarch64-linux-gnu-c++
          
          for tool in ar ranlib nm strip objcopy objdump readelf size strings; do
            ln -sf "/usr/bin/llvm-$tool" "$(pwd)/bin/$tool"
            ln -sf "/usr/bin/llvm-$tool" "$(pwd)/bin/aarch64-linux-gnu-$tool"
          done
          
          ln -sf /usr/bin/ld.lld $(pwd)/bin/ld
          ln -sf /usr/bin/ld.lld $(pwd)/bin/aarch64-linux-gnu-ld
          
          export PATH="$(pwd)/bin:/usr/lib/ccache:$PATH"

          
          #export PKG_CONFIG_PATH="$(find "$LIBDIR" -type d -name 'pkgconfig' -exec printf '%s:' {} +)$PKG_CONFIG_PATH"
          
          #echo "target_link_libraries(blender PRIVATE -fopenmp \"$LIBDIR/x265/lib/libx265.a\" \"$LIBDIR/x264/lib/libx264.a\" \"$LIBDIR/aom/lib/libaom.a\" \"$LIBDIR/vpx/lib/libvpx.a\" \"$LIBDIR/tiff/lib/libtiff.a\" \"$LIBDIR/deflate/lib/libdeflate.a\")" >> blender/source/creator/CMakeLists.txt
          
          mkdir -p build_blender && cd build_blender
                   
          cmake ../blender \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld -Wl,--undefined-version" \
            -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld -Wl,--undefined-version" \
            -DCMAKE_MODULE_LINKER_FLAGS="-fuse-ld=lld -Wl,--undefined-version" \
            -DCMAKE_BUILD_TYPE=Release \
            -DLIBDIR="$LIBDIR" \
            -DPYTHON_VERSION=3.11 \
            -DWITH_INSTALL_PORTABLE=ON \
            -DWITH_CYCLES=ON \
            -DWITH_CYCLES_DEVICE_CUDA=OFF \
            -DWITH_CYCLES_DEVICE_OPTIX=OFF \
            -DWITH_CYCLES_DEVICE_HIP=OFF \
            -DWITH_CYCLES_DEVICE_SYCL=OFF \
            -DWITH_CYCLES_DEVICE_ONEAPI=OFF \
            -DWITH_CYCLES_DEVICE_METAL=OFF 
            
          make -j$(nproc)
          make install
            
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: blender-4.2-aarch64-binary
          path: build_blender/bin/
          if-no-files-found: error
